url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Shloka V. Janapaty" # the name of your site, e.g. ACME Corp.
description: "Ecological Complexity"
theme: academic-jekyll-theme
